apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-job
  namespace: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}-job
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: cleanup-sa
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        env:
          - name: RELEASE_NAME
            value: {{ .Release.Name | quote }}
        command:
        - /bin/sh
        - -c
        - |
          kubectl patch ingress ngrok-ingress -n k8s-insight --type merge -p '{"metadata":{"finalizers":null}}';
          kubectl patch domain dianna-beholdable-larissa-ngrok-free-dev -n "${RELEASE_NAME}" --type merge -p '{"metadata":{"finalizers":null}}';
      restartPolicy: Never