apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cleanup-role
  namespace: {{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "namespaces/finalize"]
    verbs: ["*"]    
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "patch"]
  - apiGroups: ["ingress.k8s.ngrok.com"] # Needed for the Domain resource
    resources: ["domains"]
    verbs: ["get", "list", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cleanup-rolebinding
  namespace: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: cleanup-sa
    namespace: k8s-insight
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cleanup-role

