apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-insight-pv
spec:
  capacity: 
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /home/master/dynamic-storage/k8s-insight

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k8s-insight-pvc
  namespace: k8s-insight
  labels:
    app: k8s-insight-pvc
spec:
  resources:
    requests:
      storage: 100Mi
  accessModes: 
    - ReadWriteMany
  storageClassName: manual
  volumeName: k8s-insight-pv 
